name: Continuous Integration

on:
  pull_request_target:
    branches:
      - master
    types:
      - opened
      - synchronize
  push:
    branches:
      - master

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
      - name: Cache dependencies
        uses: actions/cache@v2.1.7
        with:
          key: npm-${{ hashFiles('./package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
      - name: Format
        run: npm run format
    timeout-minutes: 5
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
      - name: Cache dependencies
        uses: actions/cache@v2.1.7
        with:
          key: npm-${{ hashFiles('./package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
      - name: Lint
        run: npm run lint
    timeout-minutes: 5
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
      - name: Cache dependencies
        uses: actions/cache@v2.1.7
        with:
          key: npm-${{ hashFiles('./package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
      - name: Spellcheck
        run: npm run spellcheck
    timeout-minutes: 5
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
      - name: Use latest npm
        run: npm install --global npm@latest
      - name: Cache dependencies
        uses: actions/cache@v2.1.7
        with:
          key: npm-${{ hashFiles('./package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      - name: Install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:coverage
      - name: Upload coverage to Coveralls
        uses: mad-it/coveralls-github-action@master
        with:
          git-branch: ${{ github.event.pull_request.head.ref || github.ref }}
          git-commit: ${{ github.event.pull_request.head.sha || github.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        node-version:
          - 20
    timeout-minutes: 5
  types:
    name: Types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
      - name: Cache dependencies
        uses: actions/cache@v2.1.7
        with:
          key: npm-${{ hashFiles('./package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
      - name: Build
        run: npm run build
      - name: Types
        run: npm run types
    timeout-minutes: 5
